# HW1

## Основні завдання

In [ ]:
import numpy as np
np.set_printoptions(suppress=True, precision=6)

In [1]:
# 1. Одновимірний масив з першими 10-ма натуральними числами
vec10 = np.arange(1, 11)
print('1) Вектор з першими 10-ма натуральними числами:')
print(vec10)

1) Вектор з першими 10-ма натуральними числами:
[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
# 2. Двовимірний масив 3x3, заповнений нулями
mat3x3_zeros = np.zeros((3,3), dtype=int)
print('\n2) 3x3 матриця нулів:')
print(mat3x3_zeros)


2) 3x3 матриця нулів:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [3]:
# 3. 5x5 випадкових цілих чисел від 1 до 10
np.random.seed(1)
mat5x5 = np.random.randint(1, 11, (5,5))
print('\n3) 5x5 матриця випадкових цілих 1..10:')
print(mat5x5)


3) 5x5 матриця випадкових цілих 1..10:
[[ 6  9 10  6  1]
 [ 1  2  8  7 10]
 [ 3  5  6  3  5]
 [ 3  5  8  8 10]
 [ 2  8  1  7 10]]


In [4]:
# 4. 4x4 випадкових дійсних чисел від 0 до 1
np.random.seed(2)
mat4x4_f = np.random.rand(4,4)
print('\n4) 4x4 матриця випадкових дійсних 0..1:')
print(mat4x4_f)


4) 4x4 матриця випадкових дійсних 0..1:
[[0.435995 0.025926 0.549662 0.435322]
 [0.420368 0.330335 0.204649 0.619271]
 [0.299655 0.266827 0.621134 0.529142]
 [0.13458  0.513578 0.18444  0.785335]]


In [5]:
# 5. Два одновимірні масиви розміром 5, поелементні операції
np.random.seed(3)
a5 = np.random.randint(1, 11, 5)
b5 = np.random.randint(1, 11, 5)
print('\n5) Масиви a5 і b5:')
print('a5 =', a5)
print('b5 =', b5)
print('\nДодавання:', a5 + b5)
print('Віднімання:', a5 - b5)
print('Поелементне множення:', a5 * b5)


5) Масиви a5 і b5:
a5 = [ 9 10  4  9  9]
b5 = [ 1  6  4 10 10]

Додавання: [10 16  8 19 19]
Віднімання: [ 8  4  0 -1 -1]
Поелементне множення: [ 9 60 16 90 90]


In [6]:
# 6. Два вектори розміром 7 і їх скалярний добуток
v1 = np.array([1.5, -2.0, 3.0, 0.5, 4.2, -1.1, 2.2])
v2 = np.array([-0.5, 3.0, 1.0, 2.0, 0.0, 4.0, -1.2])
dot = np.dot(v1, v2)
print('\n6) Вектори v1 і v2:')
print('v1 =', v1)
print('v2 =', v2)
print('Скалярний добуток v1·v2 =', dot)


6) Вектори v1 і v2:
v1 = [ 1.5 -2.   3.   0.5  4.2 -1.1  2.2]
v2 = [-0.5  3.   1.   2.   0.   4.  -1.2]
Скалярний добуток v1·v2 = -9.790000000000001


In [8]:
# 7. Дві матриці 2x2 і 2x3, випадкові цілі 1..10, перемноження
np.random.seed(4)
M2x2 = np.random.randint(1,11,(2,2))
N2x3 = np.random.randint(1,11,(2,3))

print('\n7) Матриці:')
print('M2x2 =\n', M2x2)
print('N2x3 =\n', N2x3)
prod = M2x2 @ N2x3
print('\nРезультат M2x2 @ N2x3 =\n', prod)


7) Матриці:
M2x2 =
 [[8 6]
 [2 9]]
N2x3 =
 [[ 8  9  3]
 [10  8  8]]

Результат M2x2 @ N2x3 =
 [[124 120  72]
 [106  90  78]]


In [9]:
# 8. 3x3 матриця випадкових цілих 1..10 і її обернена
np.random.seed(5)

for _ in range(100):
    A = np.random.randint(1,11,(3,3)).astype(float)
    if np.linalg.det(A) != 0:
        break
A_inv = np.linalg.inv(A)
print('\n8) Матриця A (3x3):\n', A)
print('\nОбернена матриця A^-1:\n', A_inv)


8) Матриця A (3x3):
 [[ 4.  7.  7.]
 [ 1. 10.  9.]
 [ 5.  8.  1.]]

Обернена матриця A^-1:
 [[ 0.264957 -0.209402  0.029915]
 [-0.188034  0.132479  0.123932]
 [ 0.179487 -0.012821 -0.141026]]


In [10]:
# 9. 4x4 випадкових дійсних 0..1 та транспонування
np.random.seed(6)
B = np.random.rand(4,4)
print('\n9) Матриця B (4x4):\n', B)
print('\nТранспонована B^T:\n', B.T)


9) Матриця B (4x4):
 [[0.89286  0.33198  0.821229 0.041697]
 [0.107657 0.595052 0.529817 0.418807]
 [0.335408 0.622519 0.438141 0.735882]
 [0.518036 0.578859 0.645355 0.990224]]

Транспонована B^T:
 [[0.89286  0.107657 0.335408 0.518036]
 [0.33198  0.595052 0.622519 0.578859]
 [0.821229 0.529817 0.438141 0.645355]
 [0.041697 0.418807 0.735882 0.990224]]


In [11]:
# 10. 3x4 матриця та вектор розміром 4, випадкові цілі 1..10
np.random.seed(7)
M3x4 = np.random.randint(1,11,(3,4))
v4 = np.random.randint(1,11,4)
res = M3x4 @ v4
print('\n10) M3x4 =\n', M3x4)
print('v4 =', v4)
print('\nM3x4 @ v4 =', res)


10) M3x4 =
 [[ 5 10  7  4]
 [ 4  8  8 10]
 [ 8  9 10  9]]
v4 = [8 7 5 1]

M3x4 @ v4 = [149 138 186]


In [12]:
# 11. 2x3 матриця та вектор розміром 3, випадкові дійсні 0..1
np.random.seed(8)
M2x3f = np.random.rand(2,3)
v3f = np.random.rand(3)
res2 = M2x3f @ v3f
print('\n11) M2x3f =\n', M2x3f)
print('v3f =', v3f)
print('\nM2x3f @ v3f =', res2)


11) M2x3f =
 [[0.873429 0.968541 0.869195]
 [0.530856 0.232728 0.011399]]
v3f = [0.430469 0.402351 0.522675]

M2x3f @ v3f = [1.219984 0.328113]


In [13]:
# 12. Поелементне множення двох матриць 2x2
np.random.seed(9)
A2 = np.random.randint(1,11,(2,2))
B2 = np.random.randint(1,11,(2,2))
elem_mul = A2 * B2
print('\n12) A2 =\n', A2)
print('B2 =\n', B2)
print('\nПоелементне множення A2 * B2 =\n', elem_mul)


12) A2 =
 [[6 7]
 [9 7]]
B2 =
 [[2 7]
 [5 9]]

Поелементне множення A2 * B2 =
 [[12 49]
 [45 63]]


In [14]:
# 13. Добуток двох матриць 2x2
np.random.seed(10)
C2 = np.random.randint(1,11,(2,2))
D2 = np.random.randint(1,11,(2,2))
mat_prod = C2 @ D2
print('\n13) C2 =\n', C2)
print('D2 =\n', D2)
print('\nМатричний добуток C2 @ D2 =\n', mat_prod)


13) C2 =
 [[10  5]
 [ 1  2]]
D2 =
 [[10  1]
 [ 2  9]]

Матричний добуток C2 @ D2 =
 [[110  55]
 [ 14  19]]


In [15]:
# 14. 5x5 випадкових цілих 1..100 та сума елементів
np.random.seed(11)
M5x5_100 = np.random.randint(1,101,(5,5))
total_sum = M5x5_100.sum()
print('\n14) M5x5_100 =\n', M5x5_100)
print('\nСума елементів =', total_sum)


14) M5x5_100 =
 [[26 64 81 92 82]
 [56 14 77 34 72]
 [83 25 93 49 33]
 [46  5 35 13  2]
 [75 38 85 82 92]]

Сума елементів = 1354


In [16]:
# 15. Різниця двох матриць 4x4
np.random.seed(12)
E4 = np.random.randint(1,11,(4,4))
F4 = np.random.randint(1,11,(4,4))
diff = E4 - F4
print('\n15) E4 =\n', E4)
print('F4 =\n', F4)
print('\nE4 - F4 =\n', diff)


15) E4 =
 [[ 7  2  3  4]
 [ 4  1  7  2]
 [ 5  6 10  3]
 [ 7  1  6  9]]
F4 =
 [[ 3 10  4  5]
 [ 4  2  8  1]
 [ 3  7  3  1]
 [ 5  7 10  1]]

E4 - F4 =
 [[ 4 -8 -1 -1]
 [ 0 -1 -1  1]
 [ 2 -1  7  2]
 [ 2 -6 -4  8]]


In [17]:
# 16. 3x3 випадкових дійсних 0..1 та вектор-стовпчик сум по рядках
np.random.seed(13)
G3 = np.random.rand(3,3)
row_sums = G3.sum(axis=1).reshape(-1,1)
print('\n16) G3 =\n', G3)
print('\nВектор-стовпчик сум рядків =\n', row_sums)


16) G3 =
 [[0.777702 0.237541 0.824279]
 [0.965749 0.972601 0.453449]
 [0.609042 0.775527 0.641613]]

Вектор-стовпчик сум рядків =
 [[1.839522]
 [2.3918  ]
 [2.026182]]


In [18]:
# 17. 3x4 матриця з довільними цілими числами і матриця квадратів
H3x4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
H_sq = H3x4 ** 2
print('\n17) H3x4 =\n', H3x4)
print('\nКвадрати H3x4 =\n', H_sq)


17) H3x4 =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Квадрати H3x4 =
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [19]:
# 18. Вектор розміром 4 випадкових цілих 1..50 та вектор квадратних коренів
np.random.seed(14)
v4_50 = np.random.randint(1,51,4)
v4_sqrt = np.sqrt(v4_50)
print('\n18) v4_50 =', v4_50)
print('Квадратні корені:', v4_sqrt)


18) v4_50 = [44 25 13 23]
Квадратні корені: [6.63325  5.       3.605551 4.795832]


## Додаткові


In [20]:
# D1. Замініть усі непарні числа в arr на -1
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr_mod = arr.copy()
arr_mod[arr_mod % 2 == 1] = -1
print('D1) arr_mod =', arr_mod)

D1) arr_mod = [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [21]:
# D2. Перетворіть 1D-масив на 2D-масив із 2 рядками
a = np.arange(8)
a2d = a.reshape(2, -1)
print('D2) a =', a)
print('a reshape to 2 rows:\n', a2d)

D2) a = [0 1 2 3 4 5 6 7]
a reshape to 2 rows:
 [[0 1 2 3]
 [4 5 6 7]]


In [22]:
# D3. Створіть два 2D масиви та складіть їх вертикально
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
vert = np.vstack((A,B))
print('D3) A=\n',A)
print('B=\n',B)
print('\nВертикальне складання:\n', vert)

D3) A=
 [[1 2 3]
 [4 5 6]]
B=
 [[ 7  8  9]
 [10 11 12]]

Вертикальне складання:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
# D4. Створіть шаблон на основі a = np.array([1,2,3])
a = np.array([1,2,3])
out_correct = np.concatenate([np.repeat(a, 3), np.tile(a, 6)])[:18]
print('D4) out =', out_correct)

D4) out = [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [25]:
# D5. Спільні елементи між a і b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.intersect1d(a, b)
print('D5) Спільні елементи:', common)

D5) Спільні елементи: [2 4]


In [26]:
# D6. Позиції перших 5 максимальних значень
np.random.seed(100)
a = np.random.uniform(1,50,20)
# отримати індекси сортування по спаданням і взяти перші 5
idx_desc = np.argsort(a)[::-1]
top5_idx = idx_desc[:5]
print('D6) Масив a:\n', a)
print('Позиції перших 5 максимальних значень:', top5_idx)
print('Значення топ-5:', a[top5_idx])

D6) Масив a:
 [27.626842 14.6401   21.801362 42.39403   1.231224  6.956887 33.866705
 41.466785  7.698623 29.179573 44.674776 11.250904 10.081083  6.310468
 11.765177 48.952565 40.772474  9.42511  40.995013 14.429614]
Позиції перших 5 максимальних значень: [15 10  3  7 18]
Значення топ-5: [48.952565 44.674776 42.39403  41.466785 40.995013]


In [27]:
# D7. Видалити всі значення NaN з одновимірного масиву
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
clean = a[~np.isnan(a)]
print('D7) original:', a)
print('Без NaN:', clean)

D7) original: [ 1.  2.  3. nan  5.  6.  7. nan]
Без NaN: [1. 2. 3. 5. 6. 7.]


In [28]:
# D8. Евклідова відстань між двома масивами a і b
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
dist = np.linalg.norm(a - b)
print('D8) Евклідова відстань:', dist)

D8) Евклідова відстань: 6.708203932499369


In [29]:
# D9. Індекс 5-го повторення числа 1 у масиві x
x = np.array([1,2,1,1,3,4,3,1,1,2,1,1,2])
idxs = np.where(x == 1)[0]
print('D9) Індекси одиниць:', idxs)
if idxs.size >= 5:
    print('Індекс 5-го повторення (0-based):', idxs[4])
else:
    print('Менше ніж 5 повторень')

D9) Індекси одиниць: [ 0  2  3  7  8 10 11]
Індекс 5-го повторення (0-based): 8


In [31]:
# D10. Позначити повторювані записи (від 2-го випадку повторення і далі) як True
np.random.seed(100)
a = np.random.randint(0,5,10)
seen = {}
mask = np.zeros(a.shape, dtype=bool)
for i, val in enumerate(a):
    if val in seen:
        mask[i] = True
    else:
        seen[val] = 1
print('D10) a =', a)
print('Повторення з другого випадку:', mask)

D10) a = [0 0 3 0 2 4 2 2 2 2]
Повторення з другого випадку: [False  True False  True False False  True  True  True  True]
